"""Initial migration

Revision ID: 397d54f099b7
Revises:
Create Date: 2026-09-22 18:42:43.858173

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "397d54f099b7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
