"""Add composite indexes for query performance

Revision ID: 921a83407831
Revises: 397d54f099b7
Create Date: 2026-09-22 19:18:29.051100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921a83407831'
down_revision: Union[str, Sequence[str], None] = '397d54f099b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_alerts_ack_time', 'alerts', ['acknowledged', 'created_at'], unique=False)
    op.create_index('ix_alerts_type_time', 'alerts', ['alert_type', 'created_at'], unique=False)
    op.create_index('ix_events_classification_time', 'events', ['classification', 'timestamp'], unique=False)
    op.create_index('ix_events_ip_service', 'events', ['source_ip', 'service'], unique=False)
    op.create_index('ix_events_service_time', 'events', ['service', 'timestamp'], unique=False)
    op.create_index('ix_events_threat_score_time', 'events', ['threat_score', 'timestamp'], unique=False)
    op.create_index('ix_incidents_assignee_time', 'incidents', ['assignee_id', 'first_seen'], unique=False)
    op.create_index('ix_incidents_classification_time', 'incidents', ['classification', 'first_seen'], unique=False)
    op.create_index('ix_incidents_ip_time', 'incidents', ['source_ip', 'first_seen'], unique=False)
    op.create_index('ix_incidents_status_risk', 'incidents', ['status', 'risk_level'], unique=False)
    op.create_index('ix_ip_stats_blocked_score', 'ip_stats', ['is_blocked', 'threat_score'], unique=False)
    op.create_index('ix_ip_stats_country', 'ip_stats', ['country'], unique=False)
    op.create_index('ix_sessions_risk_time', 'sessions', ['risk_level', 'started_at'], unique=False)
    op.create_index('ix_sessions_service_time', 'sessions', ['service', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_service_time', table_name='sessions')
    op.drop_index('ix_sessions_risk_time', table_name='sessions')
    op.drop_index('ix_ip_stats_country', table_name='ip_stats')
    op.drop_index('ix_ip_stats_blocked_score', table_name='ip_stats')
    op.drop_index('ix_incidents_status_risk', table_name='incidents')
    op.drop_index('ix_incidents_ip_time', table_name='incidents')
    op.drop_index('ix_incidents_classification_time', table_name='incidents')
    op.drop_index('ix_incidents_assignee_time', table_name='incidents')
    op.drop_index('ix_events_threat_score_time', table_name='events')
    op.drop_index('ix_events_service_time', table_name='events')
    op.drop_index('ix_events_ip_service', table_name='events')
    op.drop_index('ix_events_classification_time', table_name='events')
    op.drop_index('ix_alerts_type_time', table_name='alerts')
    op.drop_index('ix_alerts_ack_time', table_name='alerts')
    # ### end Alembic commands ###
